### ISSUE TITLE
Desktop or embedded?

### ISSUE THREAD

**Issue by White-Rabbit-Scientific** [rust-embedded-community/usbd-serial#49]
Desktop or embedded?

**Comment by eldruin** [comment]
Please elaborate your question. What is your actual use case?

**Comment by listentodella** [comment]
can this crate run on the Desktop to read or write a cdc device ? Or this crate can only used as to create a cdc device for the embedded devices?

**Comment by mvirkkunen** [comment]
This crate is meant to be used on embedded devices to implement a CDC serial port. If you want to access such a port from a normal computer, you can use e.g. https://crates.io/crates/serialport

**Comment by listentodella** [comment]
Thanks! I'm looking for such crate for hours!
